### ISSUE TITLE
[BUG] alamedaai pod process call trace after running several hours

### ISSUE THREAD

**Issue by HungoHung** [containers-ai/alameda#469]
Env:
federatorai-operator 0.2.2 + alameda 0.3.9
172.31.5.206

Result:
alamedaai pod process call trace after running several hours

alamedaai logs:

Predict unit POD {'namespace': 'rook-ceph', 'name': 'rook-ceph-mds-myfs-7464d89445-z9djg'} data were queried.
Prediction: unit=POD,id={'namespace': 'rook-ceph', 'name': 'rook-ceph-mds-myfs-7464d89445-z9djg'},name=rook-ceph-mds-myfs,type=MEMORY_USAGE_BYTES,mid=30s
Process Process-1:7659:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "workload_predictor.py", line 158, in services.orchestra.workload_prediction.workload_predictor.WorkloadPredictor._predict_by_series.predict_subprocess
  File "sarimax_predictor.py", line 195, in services.orchestra.workload_prediction.sarimax_predictor.SARIMAXPredictor.predict
  File "/venv/lib64/python3.6/site-packages/sklearn/preprocessing/data.py", line 402, in inverse_transform
    force_all_finite="allow-nan")
  File "/venv/lib64/python3.6/site-packages/sklearn/utils/validation.py", line 568, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/venv/lib64/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains infinity or a value too large for dtype('float64').
Predict unit NODE h5-206 data were queried.
Prediction: unit=NODE,id=h5-206,name=h5-206,type=MEMORY_USAGE_BYTES,mid=30s

**Comment by HungoHung** [comment]
Move to alameda ai project
